# Generated by Django 3.2.12 on 2022-02-16 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_rename_categoria_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='nombre',
            new_name='name',
        ),
    ]
