# Generated by Django 3.2.12 on 2022-03-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tlf', models.CharField(default='', max_length=15)),
                ('debt', models.FloatField(default=0)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
