# Generated by Django 3.2.12 on 2022-03-03 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0005_rename_nombre_product_name'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_date', models.DateTimeField(auto_now_add=True)),
                ('total', models.FloatField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='Sell_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.FloatField()),
                ('total', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
                ('sell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sells.sell')),
            ],
        ),
        migrations.AddField(
            model_name='sell',
            name='product',
            field=models.ManyToManyField(blank=True, through='sells.Sell_Product', to='stock.Product'),
        ),
    ]
